### ISSUE TITLE
Add composer

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto-bulk-upload#10]
## Todo

- [ ] Add a composer.json file
- [ ] Update the folder structure
- [ ] Register the package to Packagist.
